### ISSUE TITLE
uploade image to mysql data base failure

### ISSUE THREAD

**Issue by PooryaShadfar** [BanShee8/simple-online-library#1]
my codes are  works fine and save bookname bookdate  and author name in mysql data base but its save nothing for images in data base i put image type row to blob have no idea why its dont save any thing at all. if anybody interested to my project please help me to solve this problem and fix upload issue.

**Comment by mlukac89** [comment]
You need a form to upload file
```
<form enctype="multipart/form-data" action="" method="POST">
    Send this file: <input name="images" type="file" />
    <input type="submit" value="Send File" />
</form>
```

**Comment by PooryaShadfar** [comment]
okay i use form and i changesome of my javascripts codes in index.php now file name saved to DB and show's in table but images dont move to my uploade folders.

**Comment by mlukac89** [comment]
Did you give folder permissions images to 0775 ?
First check if folder exists, if folder is writable, and make a check if file is moved
```
$uploaded = move_uploaded_file($_FILES["image"]["tmp_name"], $dir. $_FILES["image"]["name"]);
if ($uploaded) {}
```

**Comment by PooryaShadfar** [comment]
thanks for your answer, yes folder permissions is 0775 ,and yes folder exists and no file dont moved at all i guess i have some problem in following javascript codes in index.php.

```
      $(document).on('click', '#btn_add', function(){  
           var bookname = $('#ibookname').text();  
           var bookauthor = $('#ibookauthor').text();  
		   var bookpages = $('#ibookpages').text();  
		   var image = $('#file').val();  
           if(bookname == '')  
           {  
                alert("input book name please!");  
                return false;  
           }  
           if(bookauthor == '')  
           {  
                alert("input book author please!");  
                return false;  
           }  
		   if(bookpages == '')  
           {  
                alert("input book page numbers please!");  
                return false;  
           }  
		    if(image == '')  
           {  
                alert("input book cover please!");  
                return false;  
           }  
           $.ajax({  
                url:"insert.php",  
                method:"POST",  
                data:{bookname:bookname, bookauthor:bookauthor, bookpages:bookpages, image:image},  
                //dataType:"text",
                success:function(data)  
                {  
                     //alert(data);  
                     fetch_data();  
                }  
           })  
		   
      });
```

**Comment by mlukac89** [comment]
Try this first without javascript it works 100%
```
<?php
require_once 'db.php';

// folder for images
$dir = "uploads/";

// process form
if (isset($_POST['submit'])) {
  	
  	// check if folder exists
  	if (file_exists($dir)) {

  		// get post values
  		$bookname 	= mysqli_real_escape_string($connect, $_POST['bookname']);
  		$bookauthor = mysqli_real_escape_string($connect, $_POST['bookauthor']);
  		$bookpages 	= mysqli_real_escape_string($connect, $_POST['bookpages']);

  		$file = $_FILES["image"]["name"];
		$files =  basename($file);

		// if file is uploaded, insert image name into database
		if (move_uploaded_file($_FILES["image"]["tmp_name"], $dir. $_FILES["image"]["name"])) {
			
			// query
			$sql = "INSERT INTO test1 (bookname, bookauthor, bookpages , images) VALUES ('$bookname', '$bookauthor', '$bookpages', '$files')";  
			$query = mysqli_query($connect, $sql);

			// check if query is inserted by getting last inserted id
			if (mysqli_insert_id($connect)) {   
		    	echo 'Data created!';  
			} else {
				echo 'Data not created ' . mysqli_error($connect);
			}

		} else {
			echo 'Can\'t upload image, please try again.';
		}

  	} else {
  		echo 'Folder don\'t exists.';
  	}
}  
  
?>

<form enctype="multipart/form-data" action="" method="POST">
    <input type="text" name="bookname" placeholder="Bookname" required><br>
    <input type="text" name="bookauthor" placeholder="Bookauthor" required><br>
    <input type="text" name="bookpages" placeholder="Bookpages" required><br>
    Image: <input name="image" type="file" required><br>
    <input type="submit" name="submit" value="Submit">
</form>
```

**Comment by PooryaShadfar** [comment]
thanks for your answer and your time sir,but i already know your codes work 100% but i want use javascript  and ajax ,between now every thing is okay and works file only problem i have is images wont move to images folder so they dont show up. also you can test and watch online version of my work [here ](http://pgraph.ir/grid2/) as you can see, you can edit,add and delete data ajax without any loading only problem is images dont move to images folder and in have no idea why :( just one image shows correct and i copy paste that one to test if my codes works fine.

**Comment by mlukac89** [comment]
I'm downloaded yours code and try it, when i turn error_reporting(E_ALL); i get error messages and i can't insert data in table. I'm using php 7+. Btw i inserted 1 row manually from phpmyadmin and look how it all looks. 
http://prntscr.com/ex3b0l
http://prntscr.com/ex3b62

**Comment by PooryaShadfar** [comment]
did you try to add data with my form after that? you can see its works fine in my [online preview ](http://pgraph.ir/grid2/) with out any error even when i use  error_reporting(E_ALL);  too also i use php 7+

**Comment by mlukac89** [comment]
Problem was in table column names. Btw as i research a bit for your adding image like blob, you need a form with enctype="multipart/form-data" to be able to upload image into database. I that you need to check this 2 videos, its simple.
https://www.youtube.com/watch?v=4ZpqQ3j1o2w
https://www.youtube.com/watch?v=kPGxWaIhLmk

**Comment by PooryaShadfar** [comment]
hey i just fix all of my issue's and nearly compelete my project thanks for your anwsers sir.
